name = "edge-notes"
compatibility_date = "2024-11-20"
pages_build_output_dir = "./public"

## Pages config: use top-level pages_build_output_dir; project name via CLI

# Bindings
[[kv_namespaces]]
binding = "NOTES_KV"
id = "9258fcb1542b461bba118f6692fe64cd"

[vars]
TURNSTILE_SITE_KEY = "0x4AAAAAACGDYOUZ7rQLmpab"

[ai]
binding = "AI"


